### ISSUE TITLE
DATA: Add a trash button to each row

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#15]
# Description

For each row add a trash icon that will delete that entry from the table and delete the corresponding file from the POD.

# Why

So that a user can remove any data they want, perhaps because it was just a test and no longer wanted.

# Closing Criteria

- [ ]  Delete functionality available in the app

**Comment by kimishidairessha** [comment]
Delete chosen row in the table and also delete corresponding file in the Pod. Add 'refresh' Icon button. Because tooltip data and main data(which record the max value) use the same 'date', when delete the main data may affect display for tooltip data on the Table. After refresh, reset main data then tooltip data still display on the Table. For example:

If we want to delete these three data:


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/344a36f4-330e-4d27-8e3f-8d1639d02468)

Delete data from 12 Nov:


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/db2ee89c-f47a-4972-91a4-13b105843211)

Now delete data from 16 Nov, if we delete the first row(main data from that day) first, the tooltip data will disappear as well:


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/0760bd05-8fbe-4c5c-8036-104802bf3fa6)

The Pod deletion rule is only related to the 12 numbers of date and time and has nothing to do with whether it's main data or tooltip data. So I add the 'refresh' button. After refresh, the tooltip data will be the new main data:


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/43b7d802-6abc-4f42-99ee-6a4519ae26b8)

Delete the last one:


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/b4af4abe-ac14-4205-8c7b-f4ec30fe7194)

Corresponding file in the Pod also be deleted:


![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/ce4b4eb9-a683-48db-af82-eae1d6e51d54)
