### ISSUE TITLE
IMPORT: chrome import fails with *On web `path` is always `null`*

### ISSUE THREAD

**Issue by gjwgit** [kimishidairessha/secureDiaLog#44]
# Description

Trying to import a csv file on chrome version results in:

```
Error while importing CSV:       On web `path` is always `null`,
      You should access `bytes` property instead,
      Read more about it [here](https://github.com/miguelpruivo/flutter_file_picker/wiki/FAQ)
```

**Comment by kimishidairessha** [comment]
![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/b1eaea36-39de-448c-893e-a6b27fb1b4ca)



![Image](https://github.com/kimishidairessha/secureDiaLog/assets/138195672/7ecad5b9-b92d-46cd-a415-e4b0ac61d2fa)

It works fine for web now. But I do not know if it is due to my network problems, the loading time is a little long.
